version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: asset-management-app:latest
    container_name: asset-management-app
    env_file: .env
    environment:
      - PORT=${APP_PORT:-8000}
    volumes:
      - ./data:/app/data
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: asset-management-nginx
    env_file: .env
    ports:
      - "${NGINX_PUBLIC_PORT:-80}:${NGINX_PORT:-80}"
    environment:
      - NGINX_PORT=${NGINX_PORT:-80}
      - APP_PORT=${APP_PORT:-8000}
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ./app/static:/app/static:ro
    depends_on:
      - app
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
